version: '3.8'
services:
  deployer:
    container_name: deployer_node
    build:
      context: docker/deployer
    volumes:
      - './:/usr/app'
    working_dir: '/usr/app'
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://docker:2375
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always
    depends_on:
      - docker
  docker:
    container_name: deployer_docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR:
