version: '3.8'
services:
  node:
    container_name: deployer_node
    build:
      context: docker/node
    volumes:
      - './:/usr/app'
    working_dir: '/usr/app'
    env_file:
      - .env
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always
    depends_on:
      - docker
  docker:
    container_name: deployer_docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR:
